//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

/*
 * This entity was created via the sea-orm cli:
 * sea-orm-cli generate entity \
        -u postgres://app:secret@localhost:5432/kronos_db \
        -o src/entities
*/

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "test_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub text: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
