services:
  front:
  # This is the nginx reverse proxy for serving the frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend_kronos
    ports:
      - "9000:80"
      - "8001:8000"
    restart: always
    environment:
       - VITE_APP_BACKEND_ADDRESS=https://localhost/ops/
  
  webserver:
  # This is the API server connecting the db to the frontend
    build:
      dockerfile: Dockerfile
      context: ./backend_kronos
    ports: 
      - "8000:8000"
      - "9002:5432"
    
  
  database:
  # This is the Postgres instance that we'll be using
    image: postgres:latest
    restart: always
    # restart: unless-stopped

    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      # syntax is local:container
      - postgres-data:/var/lib/postgresql/data
    environment:
      # change in prod
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

#Postgres needs a place locally to save data between instantiations...in prod, this has to be a dedicated server.
volumes:
  postgres-data: