//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "paragraph")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub kronos_order: i32,
    pub parent_paragraph: Option<i32>,
    pub ordinal_sequence: i32,
    pub title: String,
    pub text: String,
    pub indent_level: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kronos_order::Entity",
        from = "Column::KronosOrder",
        to = "super::kronos_order::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    KronosOrder,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentParagraph",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl Related<super::kronos_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KronosOrder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
