//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub use super::order::Entity as Order;
pub use super::paragraph::Entity as Paragraph;
pub use super::plan::Entity as Plan;
pub use super::test_table::Entity as TestTable;
pub use super::unit::Entity as Unit;
