#! backend_configuration.yaml
application_port: 8000
application_address: 127.0.0.1
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "kronos_db"
  # TODO: CHANGE THE BELOW IN PROD
  superuser: postgres
  superuser_pwd: password
  app_user: app
  app_user_pwd: secret
  app_db_name: kronos_db
