//! army_Rank_enum.rs

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Rank {
    PV1,
    PV2,
    PFC,
    SPC,
    CPL,
    SGT,
    SSG,
    SFC,
    MSG,
    FirstSergeant,
    SGM,
    CSM,
    SMA,
    WO1,
    CW2,
    CW3,
    CW4,
    CW5,
    SecondLT,
    FirstLT,
    CPT,
    MAJ,
    LTC,
    COL,
    BG,
    MG,
    LTG,
    GEN,
    GA,
    CTR,
    GS1,
    GS2,
    GS3,
    GS4,
    GS5,
    GS6,
    GS7,
    GS8,
    GS9,
    GS10,
    GS11,
    GS12,
    GS13,
    GS14,
    GS15,
    SES1,
    SES2,
    SES3,
    SES4,
}

impl Rank {
    pub fn as_str(&self) -> &'static str {
        match self {
            Rank::PV1 => "PV1",
            Rank::PV2 => "PV2",
            Rank::PFC => "PFC",
            Rank::SPC => "SPC",
            Rank::CPL => "CPL",
            Rank::SGT => "SGT",
            Rank::SSG => "SSG",
            Rank::SFC => "SFC",
            Rank::MSG => "MSG",
            Rank::FirstSergeant => "1SG",
            Rank::SGM => "SGM",
            Rank::CSM => "CSM",
            Rank::SMA => "SMA",
            Rank::WO1 => "WO1",
            Rank::CW2 => "CW2",
            Rank::CW3 => "CW3",
            Rank::CW4 => "CW4",
            Rank::CW5 => "CW5",
            Rank::SecondLT => "2LT",
            Rank::FirstLT => "1LT",
            Rank::CPT => "CPT",
            Rank::MAJ => "MAJ",
            Rank::LTC => "LTC",
            Rank::COL => "COL",
            Rank::BG => "BG",
            Rank::MG => "MG",
            Rank::LTG => "LTG",
            Rank::GEN => "GEN",
            Rank::GA => "GA",
            Rank::CTR => "CTR",
            Rank::GS1 => "GS1",
            Rank::GS2 => "GS2",
            Rank::GS3 => "GS3",
            Rank::GS4 => "GS4",
            Rank::GS5 => "GS5",
            Rank::GS6 => "GS6",
            Rank::GS7 => "GS7",
            Rank::GS8 => "GS8",
            Rank::GS9 => "GS9",
            Rank::GS10 => "GS10",
            Rank::GS11 => "GS11",
            Rank::GS12 => "GS12",
            Rank::GS13 => "GS13",
            Rank::GS14 => "GS14",
            Rank::GS15 => "GS15",
            Rank::SES1 => "SES1",
            Rank::SES2 => "SES2",
            Rank::SES3 => "SES3",
            Rank::SES4 => "SES4",
        }
    }

    pub fn as_long_str(&self) -> &'static str {
        match self {
            Rank::PV1 => "Private",
            Rank::PV2 => "Private",
            Rank::PFC => "Private First Class",
            Rank::SPC => "Specialist",
            Rank::CPL => "Corporal",
            Rank::SGT => "Sergeant",
            Rank::SSG => "Staff Sergeant",
            Rank::SFC => "Sergeant First Class",
            Rank::MSG => "Master Sergeant",
            Rank::FirstSergeant => "First Sergeant",
            Rank::SGM => "Sergeant Major",
            Rank::CSM => "Command Sergeant Major",
            Rank::SMA => "Sergeant Major of the Army",
            Rank::WO1 => "Warrant Officer 1",
            Rank::CW2 => "Chief Warrant Officer 2",
            Rank::CW3 => "Chief Warrant Officer 3",
            Rank::CW4 => "Chief Warrant Officer 4",
            Rank::CW5 => "Chief Warrant Officer 5",
            Rank::SecondLT => "Second Lieutenant",
            Rank::FirstLT => "First Lieutenant",
            Rank::CPT => "Captain",
            Rank::MAJ => "Major",
            Rank::LTC => "Lieutenant Colonel",
            Rank::COL => "Colonel",
            Rank::BG => "Brigadier General",
            Rank::MG => "Major General",
            Rank::LTG => "Lieutenant General",
            Rank::GEN => "General",
            Rank::GA => "General of the Army",
            Rank::CTR => "Contractor",
            Rank::GS1 => "GS-1",
            Rank::GS2 => "GS-2",
            Rank::GS3 => "GS-3",
            Rank::GS4 => "GS-4",
            Rank::GS5 => "GS-5",
            Rank::GS6 => "GS-6",
            Rank::GS7 => "GS-7",
            Rank::GS8 => "GS-8",
            Rank::GS9 => "GS-9",
            Rank::GS10 => "GS-10",
            Rank::GS11 => "GS-11",
            Rank::GS12 => "GS-12",
            Rank::GS13 => "GS-13",
            Rank::GS14 => "GS-14",
            Rank::GS15 => "GS-15",
            Rank::SES1 => "SES-1",
            Rank::SES2 => "SES-2",
            Rank::SES3 => "SES-3",
            Rank::SES4 => "SES-4",
        }
    }
}
