#! backend_configuration.yaml
application:
  port: 8000
  host: 0.0.0.0 # should be 127.0.0.1 locally, but need 0.0.0.0 to work with docker, egad.
database:
  SKIP_DOCKER: "" # Keep this empty string to always create a new database, for testing. Can be set to "1" to keep old PG instance.
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "postgres"
  # TODO: CHANGE THE BELOW IN PROD
  superuser: "postgres"
  superuser_pwd: "postgres"
  app_user: "postgres"
  app_user_pwd: "postgres"
  app_db_name: "postgres"


# In dev, this means the connectino string is: 
# postgres://postgres:postgres@localhost:5432/postgres