##! standard_fragord_contents.yaml

#WARNORD

warnord:
  - ordinal_sequence: 1
    title: "Situation"
    text: "The situation paragraph describes the conditions of the operational environment that impact operations in the following subparagraphs:"
  - ordinal_sequence: 2
    title: "Mission"
    text: "State the unit's mission—a short description of who, what (task), when, where, and why (purpose) that clearly indicates the action to be taken and the reason for doing so."
    subparagraphs: []
  - ordinal_sequence: 3
    title: "Execution"
    text: "Describe how the commander intends to accomplish the mission in terms of the commander\'s intent, concept of operations, schemes of support, tasks to subordinate units, and coordinating instructions in the subparagraphs below"
    subparagraphs: []
  - ordinal_sequence: 4
    title: "Sustainment"
    text: "Describe the concept of sustainment, including priorities of sustainment by unit or area. Include instructions for administrative movements, deployments, and transportation—or references to applicable appendixes—if appropriate. Use the following subparagraphs to provide the scheme of support for logistics, financial management, personnel, and health service support. Provide detailed instructions for each sustainment subfunctions in appendices to Annex F (Sustainment)."
    subparagraphs: []
  - ordinal_sequence: 5
    title: "Command and Signal"
    text: "Include, at a minimum, succession of command."
    subparagraphs: []
